trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.11
    displayName: 'python 3.11 installed' 
  
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest
    displayName: 'Run unit tests'

  - script: |
      mkdir -p '$(Build.ArtifactStagingDirectory)/app' |
       cp app/app.py app/test_app.py requirements.txt $(Build.ArtifactStagingDirectory)/app/
    displayName: 'Prepare application artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/app'
      artifact: 'application'
    displayName: 'Publish application artifact'
